### ISSUE TITLE
Forgotten commits/merge?

### ISSUE THREAD

**Issue by k0pernicus** [miketmoore/chess#1]
Hello!
It seems that some parts of the code have not been correctly commited/merged.

For example, in `cmd/board/board.go`, you call the method `Build` on `board`, but `Board` does not exists...
I think you wanted to call the `New` function here (and add 0. and 0. as X, Y origins?), instead of `Build`, right? :-)
I tried to modify the code in order to create a _pull request_, but there is the same mistake line 41 with the method `Draw` that does not exists anymore too...

Maybe this is related to forgotten commits?

**Comment by k0pernicus** [comment]
( _ great work btw, if I can help on this project, thank you for letting me know :-) _ )

**Comment by miketmoore** [comment]
Thanks @k0pernicus! I just removed `cmd/board/board.go` since it was my first attempt. The `cmd/chess/chess.go` file is now the actual game, with the board included. 

I will definitely reach out if I need help with the project, thanks again!
